### ISSUE TITLE
SQLite docker compose volume?

### ISSUE THREAD

**Issue by mdrideout** [bugsink/bugsink#10]
What path does this system use for sqlite? Is it possible to mount a persistent volume for the SQLite directory?

**Comment by vanschelven** [comment]
Edit again for simplicity.

The database location is determined by the env variable `DATABASE_PATH`, which is  `/data/db.sqlite3` by default.

Assuming you have a stable (see links below) docker volume set up, this will work just fine.

Original answer below:

---------------

> Is it possible to mount a persistent volume for the SQLite directory?

https://www.bugsink.com/docs/docker-install/#running-with-sqlite

Warns as such:

> Resist the temptation to mount a volume and have the SQLite database stored on that volume: SQLite and Docker’s volume system don’t play well together.

I based myself on the [slqite forum](https://sqlite.org/forum/forumpost/292a68c5e4) where Docker Volumes in combination with WAL mode (which we use) was discussed.

I thought about this for some time (I really wanted to offer both the awesomeness of SQLite and the convenience of Docker), but in the end the conclusion was clear: don't ignore warnings, because doing so will at some point lead to hard-to-trace errors, and such errors are against the "Bugsink values" (easy to deploy, low maintenance).

This leaves you with 2 options:

* Ditch Docker (instead just installing on VM / bare hardware)
* Ditch SQLite (use MySQL)

Hope that helps, even if it's disappointing.

**Comment by vanschelven** [comment]
> What path does this system use for sqlite?

In the Docker config, simply in `/app/db.sqlite3`

But given that it's not ~~recommended~~ possible to mount this file as a volume, that's really an implementation detail.

**Comment by arlyon** [comment]
I think you should make it clear that this only applies when the system is being run in a VM (such as running docker on macOS). I believe that in the vast majority of cases when running this in 'production' you will not be running in a VM but just a kernel level container which is perfectly safe to do, and is being used in production all the time.

Source: I have used a fairly popular product called litestream in the past (https://litestream.io/guides/docker/) which will live-replicate an sqlite database to some cloud storage provider and requires WAL to be enabled to function. The recommended case is running it as a sidecar which means exposing the same sqlite DB to multiple containers.

**Comment by arlyon** [comment]
Had some time to test this and it is working fine. Accompanying kubernetes definition (I have actually been testing with coreOS using podman quadlet). A catastrophic crash would lose the job queue though.

`bugsink.kube`
```systemd
[Install]
WantedBy=default.target

[Kube]
Yaml=bugsink-kube.yml
ConfigMap=bugsink-configmap.yml
```

`bugsink-kube.yml`
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: bugsink
spec:
  initContainers:
  - name: init-litestream
    image: docker.io/litestream/litestream:0.3
    args: ['restore', '-if-db-not-exists', '-if-replica-exists', '/var/lib/myapp/db.sqlite3']
    volumeMounts:
    - name: bugsink-storage
      mountPath: /var/lib/myapp:Z
    - name: bugsink-configmap
      mountPath: /etc/litestream.yml
      subPath: litestream.yml
    env:
    - name: LITESTREAM_ACCESS_KEY_ID
      value: CHANGEME
    - name: LITESTREAM_SECRET_ACCESS_KEY
      value: CHANGEME
  containers:
    - name: bugsink
      image: docker.io/bugsink/bugsink:latest
      env:
        - name: PORT
          value: "8000"
        - name: SECRET_KEY
          value: CHANGEME
        - name: CREATE_SUPERUSER
          value: admin:CHANGEME
        - name: BASE_URL
          value: https://changeme.com
        - name: BEHIND_HTTPS_PROXY
          value: True
          # if we mount this in the app folder directly the overlayfs will hide the default conf and snappea db.
        - name: DATABASE_PATH
          value: /app/db/db.sqlite3
      volumeMounts:
        - mountPath: /app/db:Z
          name: bugsink-storage
      ports:
        - name: http
          containerPort: 8000
          hostPort: 8000
    - name: litestream
      image: docker.io/litestream/litestream:0.3
      args: ['replicate']
      volumeMounts:
      - name: bugsink-storage
        mountPath: /var/lib/myapp:Z
      - name: bugsink-configmap
        mountPath: /etc/litestream.yml
        subPath: litestream.yml
      env:
      - name: LITESTREAM_ACCESS_KEY_ID
        value: CHANGEME
      - name: LITESTREAM_SECRET_ACCESS_KEY
        value: CHANGEME
      ports:
      - name: metrics
        containerPort: 9090
  volumes:
    - name: bugsink-storage
      hostPath:
        type: DirectoryOrCreate
        path: /var/home/core/bugsink
    - name: bugsink-configmap
      configMap:
        name: bugsink-configmap
```
