### ISSUE TITLE
Coolify: some Bugsink-side improvements to make Bugsink even easier to install there

### ISSUE THREAD

**Issue by vanschelven** [bugsink/bugsink#46]
Reported on Discord by @jlengrand

* If you were to add curl,
* or allow localhost to the list of allowed hosts
* (and ideally implement a health endpoint) 

we'd have healthchecks working too in there.

---------

more information needed though 😄

**Comment by jlengrand** [comment]
Coolify supports the concepts of [healthchecks](https://coolify.io/docs/knowledge-base/health-checks
) that aim at checking the health of applications and auto restart them if they're failing.

<img width="1426" alt="Image" src="https://github.com/user-attachments/assets/6987765c-66a6-4de1-9374-fd5f663f8911" />

I tried to implement this in multiple ways when adding the service but because the bugsink docker image is very minimal (which is usually a good thing :)), I wasn't able to get it to work as intended.

Note that you don't necessarily add a healthcheck endpoint to bugsink itself, it's also ok for example to HTTP GET the homepage of the application and expect a 200.

You can check many examples in [coolify/templates/compose/*.yaml](https://github.com/coollabsio/coolify/tree/main/templates/compose)

For example : 

```
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/"]
      interval: 5s
      timeout: 20s
      retries: 10
```

I ended up managing to do the request using pure Python, but it then turned out that localhost isn't in the list of allowed hosts of the image, so it is not allowed to ping itself.

To fix this :

* Make sure the docker image is allowed to ping itself
* Add a 'ping' method in [the bugsink template](https://github.com/coollabsio/coolify/blob/main/templates/compose/bugsink.yaml).
* Make a PR to Coolify

This will allow Bugsink to appear healthy when installed in Coolify, and benefit from the health restarts.

**Comment by vanschelven** [comment]
Merged coolify-side.

**Comment by anime-shed** [comment]
Can we have something similar for K8s deployment since that also requires:
```
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
```
