### ISSUE TITLE
Debug tools for email-sending

### ISSUE THREAD

**Issue by vanschelven** [bugsink/bugsink#86]
From discord, taking it here for actionability & bigger reach:

> I have all working and running, accept emails are not being send. 
> Email host and email user settings are all correct [..]

Ok, let's start debugging.
I'm also assuming you don't have and didn't have a big yellow bar at the top of the page telling you the setup is incorrect.

> Would be nice to have a test email setup in the UI.

I'll add something "soonish". Meanwhile, the "reset password" form (accessible from the login page, i.e. when logged out) might function as such. It will be explicit about the known-ness of the email-address, so if you get anything but an error message an email should be sent out.

> Also the log does not show any emails going out, are those supposed to be logged ?

The sending of emails themselves is not logged, but depending on your setup, you may get "big hints". In particular, when you are running with snappea (as per the recommended "single server" setup or anything that uses the Docker image), you should see the respective tasks showing up in the [snappea] logs.

e.g.:

```
Starting 062-713 for "users.tasks.send_reset_email" with ('foo@bar.com', 
Worker done for "users.tasks.send_reset_email" in 3.735s
```

**Comment by portalzine** [comment]
All setup and no errors on the admin interface.
Reset Password tested and connection to the server fails.

```
000-002 - ERROR   - Traceback (most recent call last):
000-002 - ERROR   -   File "/usr/local/lib/python3.12/site-packages/snappea/foreman.py", line 181, in non_failing_function
000-002 - ERROR   -     function(*inner_args, **inner_kwargs)
000-002 - ERROR   -   File "/usr/local/lib/python3.12/site-packages/users/tasks.py", line 25, in send_reset_email
000-002 - ERROR   -     send_rendered_email(
000-002 - ERROR   -   File "/usr/local/lib/python3.12/site-packages/bugsink/utils.py", line 26, in send_rendered_email
000-002 - ERROR   -     msg.send()
000-002 - ERROR   -   File "/usr/local/lib/python3.12/site-packages/django/core/mail/message.py", line 299, in send
000-002 - ERROR   -     return self.get_connection(fail_silently).send_messages([self])
000-002 - ERROR   -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
000-002 - ERROR   -   File "/usr/local/lib/python3.12/site-packages/django/core/mail/message.py", line 256, in get_connection
000-002 - ERROR   -     self.connection = get_connection(fail_silently=fail_silently)
000-002 - ERROR   -                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
000-002 - ERROR   -   File "/usr/local/lib/python3.12/site-packages/django/core/mail/__init__.py", line 51, in get_connection
000-002 - ERROR   -     return klass(fail_silently=fail_silently, **kwds)
000-002 - ERROR   -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
000-002 - ERROR   -   File "/usr/local/lib/python3.12/site-packages/django/core/mail/backends/smtp.py", line 47, in __init__
000-002 - ERROR   -     raise ValueError(
000-002 - ERROR   - ValueError: EMAIL_USE_TLS/EMAIL_USE_SSL are mutually exclusive, so only set one of those settings to True.
```

Same Server as Glitchtip and that is sending emails to the same account just fine. Just tested that again.
Using this here:

```
EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
EMAIL_URL: "smtp+tls://errors@mydomain.net:PASSWORD@mail.mydomain.net:587"
```

Current setup for Bugsink

```
      BASEURL: "https://bugs.mydomain.net/"
      EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"      
      EMAIL_HOST: mail.mydomain.net
      EMAIL_HOST_USER: errors@mydomain.net
      EMAIL_HOST_PASSWORD: PASSWORD
      EMAIL_PORT: 587
      EMAIL_TIMEOUT: 10
      DEFAULT_FROM_EMAIL: "ERRORS <errors@mydomain.net>"
      EMAIL_USE_TLS: True
      SINGLE_USER: True
      USER_REGISTRATION: CB_NOBODY
      SITE_TITLE: MAGIC_BUGS
      TIME_ZONE: Europe/Berlin
      BEHIND_HTTPS_PROXY: True
```

**Comment by vanschelven** [comment]
I see the problem:

The 2 settings EMAIL_USE_TLS/EMAIL_USE_SSL are mutually exclusive, so only
set one of those settings to True.

As per https://www.bugsink.com/docs/settings/#email

In your setup those are both true because the former is true by default,
and the latter is what you have specified. Set the first to false and you
should be good.

For Bugsink generally the former should only be default true when the
latter is not specified. I'll fix that

**Comment by portalzine** [comment]
Slam Dunk! That fixed it. Regards Alex

**Comment by danielzzz** [comment]
hi, I have a similar problem, emails silently are not being sent.

I have taken the same configuration and used it in a python script and the emails were delivered correctly.

this is my docker-compose config:

```
services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: redacted
      MYSQL_DATABASE: bugsink
    volumes:
      - my-datavolume:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -p$$MYSQL_>
      interval: 1s
      timeout: 20s
      retries: 30

  web:
    image: bugsink/bugsink
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8500:8000"
    environment:
      SECRET_KEY: redacted
      CREATE_SUPERUSER: daniel:redacted
      PORT: 8000
      DATABASE_URL: mysql://root:redacted@mysql:3306/bugsink
      BEHIND_HTTPS_PROXY: "true"
      BASE_URL: "https://redacted.com"
      EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
      EMAIL_HOST: redacted.com
      EMAIL_HOST_USER: redacted@redacted.net
      EMAIL_HOST_PASSWORD: redacted
      EMAIL_PORT: 587
      EMAIL_TIMEOUT: 10
      DEFAULT_FROM_EMAIL: "Bugsink <redacted@zelisko.net>"
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import requests; requests.get(\"http://lo....>
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  my-datavolume:
```

is there any way to get some logs for that?
